### ISSUE TITLE
I cant get the tower

### ISSUE THREAD

**Issue by sdfjihkshadjfhsadoihfkasdj** [DatJaneDoe/BTD6-Mods#1]
I cant get the sea tower what do you need for the mod to work?

**Comment by DatJaneDoe** [comment]
Do you have the latest version of ModHelper in your mods folder?

**Comment by sdfjihkshadjfhsadoihfkasdj** [comment]
No where can i find it

**Comment by sdfjihkshadjfhsadoihfkasdj** [comment]
Thanks i got it to work

**Comment by BorkacObamna** [comment]
Where do I get the newest version of ModHelper?

**Comment by modderongithub** [comment]
> Where do I get the newest version of ModHelper?

[Here](https://github.com/gurrenm3/BTD-Mod-Helper/releases/latest).
