### ISSUE TITLE
SendNextRound.dll returns error.

### ISSUE THREAD

**Issue by Nosogla** [DatJaneDoe/BTD6-Mods#10]
![stupiderror](https://user-images.githubusercontent.com/96588571/147267440-6e195e35-bce3-489e-8fb2-98b45f12f802.jpg)
That is the error I receive when loading SendNextRound.dll with NKHook6 in the MelonLoader mods folder as well. I don't know what is happening, I can't really pull anything from the error.

**Comment by Nosogla** [comment]
I would like to note that, as far as I can see, there are no dependencies that have to be externally installed. NKHook6 might have been included with the SNR (SendNextRound) DLL file (as i see the error mention NKHook6 anyways), but I wasnt sure, so i installed it to bloons anyways.

**Comment by modderongithub** [comment]
NKHook6 is depreciated. If it requires NKHook6, please find a different mod - one that requires Bloons TD 6 Mod Helper.
[Here](https://discord.com/channels/504782676331331584/741266346112974858/932220317399674911) is an example.
