### ISSUE TITLE
Vengeful wizard that spawns boss bloon (tewity video)

### ISSUE THREAD

**Issue by Tomer9978** [DatJaneDoe/BTD6-Mods#11]
Hello DatJaneDoe, I wanted to ask something. Can you send me download link to your vengeful wizard that summons boss bloon pls? i spend a lot of time trying to find the mod but i can't. Thanks

**Comment by 111LLLLOPPPP** [comment]
Hi DatjaneDoe I wonder if you can send me a download link to your vengeful wizard that summons boss bloon please.
