### ISSUE TITLE
Problem with marineful and robo spider monkey

### ISSUE THREAD

**Issue by Ricy40** [DatJaneDoe/BTD6-Mods#2]
The console says they both use the Mod ID UltraParagon so cant use both at once :(
Not a problem but id really like to aha. 
Thank you for amazing mods :)

**Comment by sdfjihkshadjfhsadoihfkasdj** [comment]
I cant get the spider monkey to work tho

**Comment by sdfjihkshadjfhsadoihfkasdj** [comment]
Hey datjanedoe add description cuz im confused what they do or how to spawn them like the spider or Reactive boss how do you make it work?

**Comment by sdfjihkshadjfhsadoihfkasdj** [comment]
Me waiting for the mods tewtiy has to appear here
