### ISSUE TITLE
how to send next round

### ISSUE THREAD

**Issue by ghost** [DatJaneDoe/BTD6-Mods#9]
mod not work

**Comment by EpicDragon171** [comment]
mod not work

**Comment by modderongithub** [comment]
Please provide more info.

**Comment by EpicDragon171** [comment]
it just dont work i don't know what to say

**Comment by EpicDragon171** [comment]
the send next round mod

**Comment by Mani-cwaf** [comment]
what doesn't work about it? what happens when you place the race button, what happens when you click the ability?
